[workspace]

members = [
    "analysis",
    # "idxpkg",
    "parser",
    "replayshark",
    # "replayserver",
]

[workspace.dependencies]
wowsunpack = { version = "0.8", default-features = false, features = ["json"] }